..E
ERROR during LuaUnit test execution:
test/test_with_err_fail_pass.lua:41: attempt to perform arithmetic on a table value

Tests with errors:
------------------
1) TestAnotherThing.test2_Err1
test/test_with_err_fail_pass.lua:41: attempt to perform arithmetic on a table value
stack traceback:
	test/test_with_err_fail_pass.lua:41: in function 'TestAnotherThing.test2_Err1'

Ran 3 tests in 0.000 seconds, 2 successes, 1 error, 9 non-selected
LuaUnit ABORTED (as requested by --error or --failure option)
